### PR TITLE
Support .js env files

### LINKED ISSUE #10: Support .js env files
This would be nice to allow things like setting defaults, and could be massaged into an alternative approach for #7.

### PR DESCRIPTION
**Pull request by jonscheiding**
Support for importing .js files as an env object, fixes #10

### CODE REVIEW

**Comment by toddbluhm** [comment]
Hey, thanks so much for this! If you could update the `README.md` and `package.json` to add your name in as a contributor that would be great. If you don't want to, just let me know and I will merge it then.

**Comment by jonscheiding** [comment]
I added my name.  Thanks for responding so quickly!

**Comment by jonscheiding** [comment]
Hey, any thoughts if/when you'll be able to merge this and update on NPM?

**Comment by toddbluhm** [comment]
Sorry about this. Its has been a crazy last few weeks. I will get this merged in and published tomorrow.

**Comment by jonscheiding** [comment]
Awesome, thanks for the response!

**Comment by toddbluhm** [comment]
Your change is now in and available in version 3.0.0. I updated a core lib and added `.env-cmdrc` support so I ended up doing a major version bump. If you run into any issues please let me know and I will fix them asap.

**Pull request merged**
