### PR TITLE
Support multiple environment  name.

### PR DESCRIPTION
**Pull request by zhrren**

### CODE REVIEW

**Comment by toddbluhm** [comment]
I am not sure I really like this change. I think instead of using an inheritance style, I would just say duplicate those values across envs. In fact, if those vars don't change from env to env...I might question why they are env vars to begin with and not just project constants. 

I get the idea of avoiding duplication and complete agree, but I just don't like this inheritance style and I am not sure I want to complicate this project anymore that it already is by adding in env inheritance. I am willing to be persuaded otherwise, but unless there is a big desire for this, I will probably just leave it open to allow for future feedback.

**Comment by louisremi** [comment]
I was just considering implementing these changes myself.

There are two reasons why I won't store the common env variables in projcet constants:
- I need them as env vars
- I cannot commit them on my repo

In my case, I'm using .env-cmdrc to store API keys and other variables required to use the Google Calendar API. I'm using the same API keys for all my environments, and simply use different calendarId between dev and prod. Here is what Google API keys and env vars look like:
image

Having to copy that in all of my environments is pretty annoying. It'd be great to have a way to factor out common env vars :-)

**Comment by louisremi** [comment]
Oh I just realized I can use a JS file to store my env vars. JS has all I need to keep my files DRY :-)

**Comment by toddbluhm** [comment]
@zhrren do you mind giving me permission to rebase this PR, or even rebasing it yourself. After thinking for a long time about this, I think the pros out way the cons (additional complexity). Thanks for your patience on this matter.

**Comment by toddbluhm** [comment]
This has now been released and included in version `6.0.0`. Thanks again for your input and contribution @zhrren.

**Pull request merged**
